### ISSUE TITLE
Cannot resolve dependency 'core-js/stable'

### ISSUE THREAD

**Issue by wdmny** [ZengineHQ/legacy-plugin-wrapper#63]
> wrapper/lib/wrapper.js:1:7: Cannot resolve dependency 'core-js/stable'

> In plugins/{plugin-name}/wrapper/lib/wrapper.js replace import core-js/stable with import @babel/polyfill.

@JoeBello

**Comment by wizehive-chrismanjoine** [comment]
fixed
